# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='follow type'),
        ),

        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('user', 'content_type', 'object_id', 'follow_type')]),
        ),
    ]
