# Generated by Django 3.0 on 2019-12-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='actor_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
