# Generated by Django 2.0.5 on 2018-05-03 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actstream_action_action_objects', related_query_name='actstream_action_action_objects', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='actor_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actstream_action_actors', related_query_name='actstream_action_actors', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actstream_action_targets', related_query_name='actstream_action_targets', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actstream_follow_follow_objects', related_query_name='actstream_follow_follow_objects', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actstream_follow_follows', related_query_name='actstream_follow_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
